version: '3.9'

services:
  postgresql:
    build:
      context: ./source/postgresql/
      target: base
    restart: always
    ports:
      - 5432:5432
    networks:
      - database_network
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    env_file:
      - ./source/postgresql/src/.env
    command: -p 5432
    tty: true
    container_name: postgresql

  frontend:
    build:
      context: ./source/frontend/
      target: base
    restart: always
    networks:
      - database_network
    ports:
      - 3000:3000
    env_file:
      - ./source/frontend/src/.env
    volumes:
      - ./source/frontend/src/:/app/
      - /app/node_modules
      - static_volume:/app/static/
    container_name: frontend

networks:
  database_network:
    driver: "bridge"

volumes:
  postgresql_volume:
  static_volume: